In [1]:
import torch
import numpy as np

In [24]:
d = torch.load("../../../data/proteinnet/casp12_190808_30.pt")

In [25]:
d.keys()

dict_keys(['train', 'valid', 'test', 'settings', 'description', 'date'])

In [26]:
d["test"].keys()

dict_keys(['seq', 'ang', 'ids', 'crd', 'mask', 'evolutionary', 'secondary'])

In [61]:
dt = d["train"]
print(dt["seq"][0])
print(dt["seq"][0].shape)
print(dt["ang"][0])
print(dt["ang"][0].shape)
print(dt["ids"][0])
print(dt["crd"][0])
print(dt["crd"][0].shape)

[[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ...  True False False]
 [False False False ... False False False]
 [False False False ... False False False]]
(234, 20)
[[        nan         nan  0.7278752  ...         nan         nan
          nan]
 [ 0.41417996 -0.91019501  0.8454803  ...         nan         nan
          nan]
 [-0.25224441 -0.96766356 -0.5593133  ...         nan         nan
          nan]
 ...
 [-0.5757264  -0.81764241 -0.30892917 ...         nan         nan
          nan]
 [-0.11674786 -0.99316159 -0.68355788 ... -0.93902553         nan
          nan]
 [-0.55922171 -0.82901814         nan ...         nan         nan
          nan]]
(234, 24)
4W8Q_1_A
[[86.67   2.207 22.978]
 [87.447  3.135 22.161]
 [86.938  3.205 20.716]
 ...
 [   nan    nan    nan]
 [   nan    nan    nan]
 [   nan    nan    nan]]
(3042, 3)


In [42]:
99*13

1287

In [43]:
for i in range(len(dt["seq"])):
    l = dt["seq"][i].shape[0]
    dt["ang"][i].shape[0] == l, f"ang and seq mismatch, {l}, {dt['ang'][i].shape}, {i}"
    assert dt["crd"][i].shape[0] == l*13

In [45]:
dt["seq"][2].shape

(98, 20)

In [84]:
for i in range(10):
    print(dt["ids"][i])
    add = 0
    if "3EAF" in dt["ids"][i]:
        add = 41
    print(np.where(np.isnan(dt["ang"][i]).all(axis=1))[0]+add)
    

4W8Q_1_A
[]
2J58_1_A
[ 33  72 173 208 238 249 254 270 304 345]
3EAF_1_A
[234 258 300 317 405]
3RZG_1_A
[]
4PR7_1_A
[ 11  12  13  14  42  43  44  45  46  47  48  49  50  51  52  53  54 117
 118 119 120 121 122 123 124 125 126 127 128 159 160 161 162 163 164 165
 166 167 168 196 197 198 199 200 201 202]
4XHT_1_A
[]
4WVU_1_A
[]
2QXX_1_A
[]
3VC5_d3vc5a1
[]
4B9I_1_A
[ 12  13  14  98  99 100 117 118 119 120 121 122]


In [85]:
AA_MAP = {'A': 0, 'C': 1, 'D': 2, 'E': 3,
          'F': 4, 'G': 5, 'H': 6, 'I': 7,
          'K': 8, 'L': 9, 'M': 10, 'N': 11,
          'P': 12, 'Q': 13, 'R': 14, 'S': 15,
          'T': 16, 'V': 17, 'W': 18, 'Y': 19}
AA_MAP_INV = {v: k for k, v in AA_MAP.items()}
def onehot_to_seq(oh):
    """ Given a vector of one-hot vectors, returns its corresponding AA sequence."""
    seq = ""
    for aa in oh:
        idx = aa.argmax()
        seq += AA_MAP_INV[idx]
    return seq

In [87]:
onehot_to_seq(dt["seq"][2])

'SLTINVGLLVDETGPTSDVGKGYSLGAELAFKYFNEKGIYTKDGVRVNINYIKRDYAYNPTTAEEYYREFRDRYGVIAIIGWGTADTEKLSDQVDTDKITYISASYSAKLLVKPFNFYPAPDYSTQACSGLAFLASEFGQGKLALAYDSKVAYSRSPIGAIKKAAPSLGLQVVGDYDLPLRATEADAERIAREMLAADPDYVWCGNTISSCSLLGRAMAKVGLDAFLLTNVWGFDERSPQLIGEGGYGKVFGISPFIYPMFGQDVEGIQTIFEAARMNGVSEDQINLRVVQGFVNVWLLIKAIESVTSQDLQERGGEALKEALEANTFDLGGITADTIDYEPGFHLAYRKVFIIKLGENGELQLMGKFEAPSQVDCARYTIEEG'